import { v4 as uuidv4 } from 'uuid';

export default {
    customers: {
        id: uuidv4(),
        name: 'customers',
        columns: [
            {
                name: 'customer_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'first_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'last_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'email',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'phone_number',
                type: 'VARCHAR',
                isNull: false,
                length: '20',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'address',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'city',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'state',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'zip_code',
                type: 'VARCHAR',
                isNull: false,
                length: '20',
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    products: {
        id: uuidv4(),
        name: 'products',
        columns: [
            {
                name: 'product_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'product_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'description',
                type: 'TEXT',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'price',
                type: 'DECIMAL(10,2)',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'in_stock_quantity',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'category_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'supplier_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
        ],
    },
    categories: {
        id: uuidv4(),
        name: 'categories',
        columns: [
            {
                name: 'category_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'category_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'description',
                type: 'TEXT',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    employees: {
        id: uuidv4(),
        name: 'employees',
        columns: [
            {
                name: 'employee_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'first_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'last_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'email',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'phone_number',
                type: 'VARCHAR',
                isNull: false,
                length: '20',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'hire_date',
                type: 'DATE',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'position',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'salary',
                type: 'DECIMAL',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    orders: {
        id: uuidv4(),
        name: 'orders',
        columns: [
            {
                name: 'order_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'customer_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'order_date',
                type: 'DATE',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'total_amount',
                type: 'DECIMAL(10,2)',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    shipments: {
        id: uuidv4(),
        name: 'shipments',
        columns: [
            {
                name: 'shipment_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'order_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'shipment_date',
                type: 'DATE',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'shipment_status',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'carrier',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'tracking_number',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    payments: {
        id: uuidv4(),
        name: 'payments',
        columns: [
            {
                name: 'payment_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'order_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'payment_date',
                type: 'DATE',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'amount',
                type: 'DECIMAL(10,2)',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'payment_method',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    suppliers: {
        id: uuidv4(),
        name: 'suppliers',
        columns: [
            {
                name: 'supplier_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'supplier_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'contact_person',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'email',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'phone_number',
                type: 'VARCHAR',
                isNull: false,
                length: '20',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'address',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'city',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'state',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'zip_code',
                type: 'VARCHAR',
                isNull: false,
                length: '20',
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    product_reviews: {
        id: uuidv4(),
        name: 'product_reviews',
        columns: [
            {
                name: 'review_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'product_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'customer_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'rating',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'review_text',
                type: 'TEXT',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'review_date',
                type: 'DATE',
                isNull: false,
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
    employee_roles: {
        id: uuidv4(),
        name: 'employee_roles',
        columns: [
            {
                name: 'employee_role_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'PK',
                shouldHighlight: false,
            },
            {
                name: 'employee_id',
                type: 'INTEGER',
                isNull: false,
                keyConstraint: 'FK',
                shouldHighlight: false,
            },
            {
                name: 'role_name',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
            {
                name: 'department',
                type: 'VARCHAR',
                isNull: false,
                length: '255',
                keyConstraint: '',
                shouldHighlight: false,
            },
        ],
    },
};
