<script setup lang="ts">
import { Handle, Position } from '@vue-flow/core';
</script>
<template>
    <Handle
        id="source-top"
        type="source"
        :position="Position.Top"
        :connectable="false"
    />
    <Handle
        id="source-bottom"
        type="source"
        :position="Position.Bottom"
        :connectable="false"
    />
    <Handle
        id="source-right"
        type="source"
        :position="Position.Right"
        :connectable="false"
    />
    <Handle
        id="source-left"
        type="source"
        :position="Position.Left"
        :connectable="false"
    />

    <Handle
        id="target-top"
        type="target"
        :position="Position.Top"
        :connectable="false"
    />
    <Handle
        id="target-bottom"
        type="target"
        :position="Position.Bottom"
        :connectable="false"
    />
    <Handle
        id="target-right"
        type="target"
        :position="Position.Right"
        :connectable="false"
    />
    <Handle
        id="target-left"
        type="target"
        :position="Position.Left"
        :connectable="false"
    />
</template>
